### ISSUE TITLE
Quadratic equation example prints NaNs

### ISSUE THREAD

**Issue by vtereshkov** [OJarrisonn/vaca#4]
Should I treat it as no solution?
```
Inform a: 3
Inform b: -5
Inform c: 8
Calculating x' and x''
x' NaN, x'' NaN
```

**Comment by nahharris** [comment]
Yes, there's an error in the Vaca code. I'm calculating

```
#(delta (brt (- (* b b) (* 4 (* a c) )) 2))
```

Which is wrong, the square root should only be calculated after checking if the inner expression is positive

It's the first Vaca logic error rather than in the interpreter

But this remainds me of adding some NaN treatment

I'll fix the example in a latter update

**Comment by vtereshkov** [comment]
I think taking the square root of a negative number should be a runtime error.

**Comment by nahharris** [comment]
ATM i added a value NaN, but i may turn it into an Error
